def tutnese(str)
  str.downcase!
  str.gsub 'b', 'bub'
  str.gsub 'c', 'cash'
  str.gsub 'd', 'dud'
  str.gsub 'f', 'fuf'
  str.gsub 'g', 'gug'
  str.gsub 'h', 'hash'
  str.gsub 'j', 'jay'
  str.gsub 'k', 'kuck'
  str.gsub 'l', 'lul'
  str.gsub 'm', 'mum'
  str.gsub 'n', 'nun'
  str.gsub 'p', 'pup'
  str.gsub 'q', 'quack'
  str.gsub 'r', 'rug'
  str.gsub 's', 'sus'
  str.gsub 't', 'tut'
  str.gsub 'v', 'vuv'
  str.gsub 'w', 'wack'
  str.gsub 'x', 'ex'
  str.gsub 'y', 'yub'
  str.gsub 'z', 'zub'
  return str
end
